### ISSUE TITLE
add tables to tables.html

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/covid19-dashboard#29]
Presently there are no tables on the _tables.html_ page, which is negatively affecting UX.
The tables to append are:
1. The already existing **_ Global Cases_** table, found on index page.
2. **Death rates by country**; would have to add a function to _getdata.py_ to create the table, show current cumulative deaths & calculated death rate.
3. any other **new** table idea that may provide value...

**Comment by mateuszz0000** [comment]
Do we use raw HTML or a library? ex https://django-tables2.readthedocs.io/en/latest/

**Comment by BrianRuizy** [comment]
The current table on the home page is just base HTML, Django tags, and using[ sorttable.js](https://kryogenix.org/code/browser/sorttable/) to handle sorting. 
```html
<table class="table align-items-center table-flush sortable">
<tbody>
    {% for i, row in cases_table.iterrows %}
        <tr>
            <td>{{ row.Country | truncatechars:14 }}</td>
...
```
Though, I see django-tables2 does **not** rely on JavaScript and "supports custom column functionality". Django-tables may be the best bet actually.

**Comment by BrianRuizy** [comment]
Tentatively removed tables page, don't see much value in it presently, compared to actual visualizations
