### ISSUE TITLE
Create html page for data sources

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/covid19-dashboard#30]
Currently, the **Data** button on the **sidenav** just points to an external URL, as data sources are increasing with more plots, it would be best to make a simple page showing all the respective data sources with clickable links. 

Create:  `covid-19-dashboard/core/templates/pages/data.html`
Bootstrap4 | List [Reference](https://getbootstrap.com/docs/4.0/components/list-group/#flush)

![Screen Shot 2020-05-11 at 1 26 54 AM](https://user-images.githubusercontent.com/23439187/81530675-f2d05000-9326-11ea-9e06-043548fd7fd1.png)

**Comment by arhamshah** [comment]
Where is source of data?

**Comment by BrianRuizy** [comment]
@arhamshah, I commented the thus far used data sources in [_covid19-dashboard/processdata/getdata.py_](https://github.com/BrianRuizy/covid19-dashboard/blob/master/processdata/getdata.py)

```python 
 8  # Datasets scraped can be found in the following URL's:
 9  # ¹ Johns Hopkins: https://github.com/CSSEGISandData/COVID-19 
10 # ² Our World In Data: https://github.com/owid/covid-19-data/tree/master/public/data
11 # ³ New York Times: https://github.com/nytimes/covid-19-data
```

I simply wanted a page (**...com/data.html**) where we numerically list the data sources with respective links.
Good first issue for prospective contributors.

**Comment by arhamshah** [comment]
assign me

**Comment by arhamshah** [comment]
Please do check my pull request...

**Comment by arhamshah** [comment]
Looking forward to many more commits!!
Issue solved.
You can close this issue!!!

**Comment by BrianRuizy** [comment]
PR: #45
