### ISSUE TITLE
Remove unused CSS for performance 

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/covid19-dashboard#44]
Upon auditing the website with Google Lighthouse, it results that the website's performance is being crucially affected by unused CSS. Which is the result of having used a boilerplate app. 

- Remove unused CSS in _/styles.css_
- Perform interface testing
- Rerun Google Lighthouse audit

**Comment by Rahmsauce** [comment]
Hello, I just found this project and was quite impressed by its functionality and user interface. However, I noticed it suffering from performance deficiencies as well and would be interested in helping out by solving this issue.

After further inspection of the website, I found out that, as you already stated, styles.css does have a fairly large share of unused code. On the other hand, styles.css only seems to be a relatively small share of the website. The largest problem seems to be plotly-latest.min.js with potential savings of more than 2 MB compared to around 350 kB from styles.css. So while I do think of removing unused CSS to be a step in the right direction, I wouldn't expect a huge performance boost from doing so.

![screenshot](https://user-images.githubusercontent.com/53840228/86589721-78225a80-bf8e-11ea-9c14-07c078ce7ee8.png)


Also, removing unused CSS will probably result in boilerplate components which haven't been used yet not working properly in the future. I am wondering if this might be a problem and if it is, how to avoid it.

**Comment by BrianRuizy** [comment]
@Rahmsauce, Thank you for your interest in contributing! 

You have a very good point, I appreciate your perspective. Indeed, it may be more cost effective to dig into _Plotly_ before removing boilerplate _CSS._

What do you think would be a good route to approach this issue?

I figured this would be an issue beforehand, since all the rendering is done at the time the user is loading the site, as opposed to having everything running on a server.

**Comment by Rahmsauce** [comment]
Concerning the unused CSS, the simplest solution I can think of is removing all unused instructions and add them back if they are needed in the future.

Regarding Plotly, I found that [this file from cloudflare](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.54.5/plotly.min.js) seems to do the job as well while being much smaller in size.

**Comment by BrianRuizy** [comment]
> The largest problem seems to be plotly-latest.min.js with potential savings of more than 2 MB compared to around 350 kB from styles.css.

@Rahmsauce, good suggestion. I think first we should try the alternative _Plotly_ CDN, since from your acquired metrics, it is many times greater in total bytes compared to CSS. Please do fork and submit a PR. 
I look forward to seeing your changes! 🙂

**Comment by Rahmsauce** [comment]
I just uploaded the pull request regarding the Plotly CDN. While the Plotly file was reduced to about half of its original size, perceived performance didn't improve a lot, to be honest. However, I believe to have found the culprit for the website's slow performance and am going to create a new issue concerning that.
