### ISSUE TITLE
Cases table is longer sortable

### ISSUE THREAD

**Issue by Rahmsauce** [BrianRuizy/covid19-dashboard#49]
I just noticed the cases table to be no longer sortable. The cause for this bug seems to be the expired certificate of https://kryogenix.org/ resulting in the browser not downloading sorttable.js. Probably, this issue is simply fixed by storing sorttable.js on the local server instead of trying to fetch it from https://kryogenix.org/.

**Comment by BrianRuizy** [comment]
#50
