### ISSUE TITLE
Unclear purpose of "-fullscreen" files

### ISSUE THREAD

**Issue by Rahmsauce** [BrianRuizy/covid19-dashboard#54]
Having spent some time with this project, I've been coming across these "-fullscreen" files:

- /core/templates/layouts/base-fullscreen.html
- /core/templates/includes/scripts-fullscreen.html
- /core/templates/includes/footer-fullscreen.html

I might have overlooked something, but each time, I wonder what their purpose could be since I don't seem them being referenced anywhere. Do you have an explanation for them?

**Comment by BrianRuizy** [comment]
As I've mentioned in the past, the project was launched using boilerplate code. Given that some sections were neglected, there could be the case where some unnecessary code is still present. 

If you see any more of this just delete, and perform simple interface testing to verify. 🙂
