### ISSUE TITLE
Mapbox

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/covid19-dashboard#62]
**Describe the bug**
Global map not working as of **11/23/2020**

**Comment by LeoHerrmann** [comment]
Hi, it seems as if the columns "Incidence_Rate" and "Case-Fatality_Ratio" of our source for daily reports have been renamed. This can be confirmed by comparing the first lines of [one of the recent files](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/11-23-2020.csv) to [one of the older ones](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/10-23-2020.csv). Simply adjusting processdata/views.py accordingly appears to fix the issue.
