### ISSUE TITLE
Inconsistent data source system vs application - ARC GIS

### ISSUE THREAD

**Issue by maagdalenakaczynska** [BrianRuizy/covid19-dashboard#70]
The data displayed in the application is inconsistent with the system specified as the source.

**To Reproduce**
1. Go to 'https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6'
2. Scroll down to widgets: Global Cases, Global Deaths
4. See error - the value is different from the value displayed in your application

**Expected behavior**
the data should not be misleading, or should contain information about the last refresh time

**Desktop (please complete the following information):**
 - OS: ios
 - Browser Chrome 
 - Version 87.0.4280.141

**Comment by BrianRuizy** [comment]
Hi @maagdalenakaczynska, 
Thanks for recognizing and opening the issues with regard to inconsistent data
