### ISSUE TITLE
Incomprehensible Logaritmic Scale

### ISSUE THREAD

**Issue by DarWik** [BrianRuizy/covid19-dashboard#98]
How does the average user know what is the Logarithmic Scale? Since it is rather linear in the media/TV? According to This is confusing to me, should be deleted.

![image](https://user-images.githubusercontent.com/73022845/105424005-ca834a00-5c46-11eb-82f1-2efa756a9d60.png)

**Comment by BrianRuizy** [comment]
I disagree, not deleted, but maybe instead defaulted to linear.

**Comment by BrianRuizy** [comment]
@DarWik, please join Gitter chat [![Gitter](https://badges.gitter.im/ncov-dashboard/community.svg)](https://gitter.im/ncov-dashboard/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by DarWik** [comment]
> @DarWik, please join Gitter chat [![Gitter](https://camo.githubusercontent.com/6a188005b65ae3df42516fe1a8ae3c2aa4ff4a6a07cb62edf26446814c0d3a0d/68747470733a2f2f6261646765732e6769747465722e696d2f6e636f762d64617368626f6172642f636f6d6d756e6974792e737667)](https://gitter.im/ncov-dashboard/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Done
